//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TimeTracker.Data
{
    public partial class Booking : BaseEntity
    {
        #region Navigation Properties
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;
    
        public virtual Project Project
        {
            get { return _project; }
            set
            {
                if (!ReferenceEquals(_project, value))
                {
                    var previousValue = _project;
                    _project = value;
                    FixupProject(previousValue);
                }
            }
        }
        private Project _project;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Bookings.Contains(this))
            {
                previousValue.Bookings.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Bookings.Contains(this))
                {
                    User.Bookings.Add(this);
                }
            }
        }
    
        private void FixupProject(Project previousValue)
        {
            if (previousValue != null && previousValue.Bookings.Contains(this))
            {
                previousValue.Bookings.Remove(this);
            }
    
            if (Project != null)
            {
                if (!Project.Bookings.Contains(this))
                {
                    Project.Bookings.Add(this);
                }
            }
        }

        #endregion
    }
}
