using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;

namespace TimeTracker.Data
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System;
    using System.Data.Objects;
    using System.Data.EntityClient;

    namespace TimeTracker.Data
    {
        public partial class TimeTrackerContext : DbContext
        {
            public const string ConnectionString = "Data Source=.;Initial Catalog=TimeTracker;Integrated Security=True";

            #region Constructors

            public TimeTrackerContext()
                : base(ConnectionString)
            {
                this.Configuration.LazyLoadingEnabled = true;
            }

            public TimeTrackerContext(string connectionString)
                : base(connectionString)
            {
                this.Configuration.LazyLoadingEnabled = true;
            }

            #endregion

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                var projectConfig = modelBuilder.Entity<Project>().Map(m =>
                                                       {
                                                           m.MapInheritedProperties();
                                                           m.ToTable("Project");
                                                       });         
                //projectConfig.HasMany(p => p.Bookings)
                //    .WithOptional()
                //    .HasForeignKey(b => b.Project);
                
                //projectConfig.HasMany(p => p.Users)
                //    .WithOptional()
                //    .HasForeignKey(user => user.Projects);


                var bookingConfig = modelBuilder.Entity<Booking>().Map(m =>
                {
                    m.MapInheritedProperties();
                    m.ToTable("Booking");
                });

                bookingConfig.HasRequired(b => b.Project).WithMany(p => p.Bookings).WillCascadeOnDelete(false);
                bookingConfig.HasRequired(b => b.User).WithMany(u => u.Bookings).WillCascadeOnDelete(false);

                var userConfig = modelBuilder.Entity<User>().Map(m =>
                {
                    m.MapInheritedProperties();
                    m.ToTable("User");
                });

                userConfig
                    .HasMany(user => user.Projects)
                    .WithMany(p => p.Users).Map(map => map.ToTable("UserProject"));
            }

            public DbSet<User> Users
            {
                get { return _users ?? (_users = Set<User>()); }
            }
            private DbSet<User> _users;

            public DbSet<Booking> Bookings
            {
                get { return _bookings ?? (_bookings = Set<Booking>()); }
            }
            private DbSet<Booking> _bookings;

            public DbSet<Project> Projects
            {
                get { return _projects ?? (_projects = Set<Project>()); }
            }
            private DbSet<Project> _projects;

        }
    }

}
